import type { Metadata } from "next";
import { Inter as FontSans, Heebo } from "next/font/google";
// import  useTriot  from './fonts/font'
import "./globals.css";
import Head from "next/head";
import Navbar from "./Navbar";
import Footer from "./Footer";

const heebo = Heebo({ subsets: ["latin"] });

import { cn } from "@/lib/utils";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Linos-Touch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <link rel="icon" href="/favicon.ico" sizes="any" />

      <body className={`${heebo.className}, ${cn(fontSans.variable)}`}>
        <Navbar />
        <main className="w-full">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
